
name: CI/CD Pipeline for Wellness Tourism Prediction

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --no-cache-dir numpy pandas scikit-learn matplotlib seaborn joblib xgboost requests huggingface_hub mlflow streamlit

    - name: Configure Hugging Face login
      run: |
        echo "${ secrets.HF_TOKEN }" | huggingface-cli login

    - name: Execute Model Training and Saving
      run: |
        python model_building/train.py
      env:
        HF_TOKEN: ${ secrets.HF_TOKEN }

    - name: Execute Deployment to Hugging Face Space
      run: |
        python hosting/hosting.py
      env:
        HF_TOKEN: ${ secrets.HF_TOKEN }

